### ISSUE TITLE
panic: runtime error: index out of range [3] with length 3

### ISSUE THREAD

**Issue by Elfonda19** [Djuk1c/zefoy-froyz-bot#4]
panic: runtime error: index out of range [3] with length 31

goroutine 1 [running]:
main.ProcessUrl({0x400001a180, 0x20})
        /data/data/com.termux/files/home/zefoy-froyz-bot/main.go:68 +0x90
main.main()
        /data/data/com.termux/files/home/zefoy-froyz-bot/main.go:41 +0x1a0

**Comment by Djuk1c** [comment]
Your URL input was incorrect.
It should look like
`https://www.tiktok.com/@djukic.dev/video/7162615834706283777`
OR
`7162615834706283777`
