### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ivannikcevicc** [Djuk1c/zefoy-froyz-bot#6]
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.ProcessUrl
        /home/kali/Desktop/zefoy-froyz-bot-main/main.go:68
main.main
        /home/kali/Desktop/zefoy-froyz-bot-main/main.go:41

**Comment by Djuk1c** [comment]
Duplicate, check this #4.

**Comment by ivannikcevicc** [comment]
> Duplicate, check this #4.

oh sry, thanks
